### ISSUE TITLE
422 HTTP error

### ISSUE THREAD

**Issue by Imorency** [MEF-GIT/MEF-LSO-Sonata-SDK#53]
How much can we add to/remove/change the codes defined with a 422 HTTP error? Depending on if some minor changes are made to the schema then some of these are not needed as they are validated using the schema itself. Code 100 is an example of this.

**Comment by bigludo7** [comment]
Hello Isabelle
For me we should still work on the list behind 422. 422 is used when a 'functionnal' error prevent to have expected behavior and an additionnal code is provided for explanation. I think we should work on this list to be sure to 1/cover main reason for 'failure' 2/ be a little bit more generic with place holder for attribute name for example. Definitively a part of the API to be improved once we'll work more at the API level.

**Comment by MichalLaczynskiAmartus** [comment]
RC5 introduces a new approach to Errors. No longer we produce subcodes for each possible thing that can happen. There are several types of errors that may occur and an extra JSONpath field that will point to the attribute causing the problem. Please refer to MEF W87.
