### ISSUE TITLE
"RelatedPlaceReforValue" Site as a type

### ISSUE THREAD

**Issue by Imorency** [MEF-GIT/MEF-LSO-Sonata-SDK#54]
The @type discriminator for "RelatedPlaceReforValue" has a possible option "Site". However, the site fields such as "siteName" and "siteCompanyName" are part of the parent object. Should "Site" be removed from the description of this discriminator?

**Comment by bigludo7** [comment]
The @type is used to define which 'kind' of site descriptor you're using. It could a site, a formattedAddress, etc... The "siteName" & "siteCompanyName" are information provided by the buyer for the future site to be generated when a 'new' place is described. 
So as a buyer you can provide a place described through a formatedAddress, provide it, and then provide SiteName and SiteCompanyName. We expect the seller to create a site related to this address and use these 2 attributes Name & CompanyName to ddefine this site (and allow buyer to retrieve it using these parameters).
Note that if you provide a site Id as a place, you should not provide SiteName & SiteCompanyName because the site exist already and the productOrder is not supposed to update the site.

**Comment by Imorency** [comment]
Actually, this issue is a small technical issue with the schema. For example, when we choose "FormattedAddress" as a @type, the discriminator resolves because a "FormattedAddress" object exists in the schema. However, when we choose "Site" as a @type, there is no "Site" object so the discriminator fails to resolve. Therefore we get an error when validating objects using this schema with our schema validator.

**Comment by bigludo7** [comment]
Oh got it ! sorry !
Not easy.... GeographicSite must be only use as a reference and never as 'value'. Nevertheless when we use it, we provide an id and we must specifiy it's a site id. Not sure it works if I had in the swagger an empty site structure. I will try or we'll have to find a smarter solution. 
Thanks Isabelle !

**Comment by Imorency** [comment]
Mariusz,  I see that you have closed this issue...  Can you please let me know how it was resolved?

**Comment by mariusz-amartus** [comment]
Isabelle, I closed all the issues addressed in the SDK R4 (API v3.0).
My understanding is that this issue was fixed by adding an empty GeographicSite structure so the "Site" value could be used as @type for RelatedPlaceReforValue.
@bigludo7, please correct me if I'm wrong.

**Comment by bigludo7** [comment]
You're right @mariusz-amartus : I've added a GeographicSite class with no attribute. For met its works.

BTW: Probably I should move the 5 site-related attributes from the RelatedPlaceRefOrValue class to ReferencedAddress, FieldedAddress, FormattedAdress & GeographicLocation and not in GeographicSite in order to prevent buyer to provide  this information when she/he refers a geosite.
